docker run -it -d \
  --label traefik.http.routers.prestigepharmacy.rule=Host\(\`prestigepharmacy.online\`\) \
  --label traefik.http.routers.prestigepharmacy.tls.certresolver=lets-encrypt \
  --label traefik.http.routers.prestigepharmacy.tls=true \
  --label traefik.http.routers.prestigepharmacy.service=prestigepharmacy-credit-http \
  --label traefik.http.services.prestigepharmacy-credit-http.loadbalancer.server.port=80 \
  --name prestigepharmacy \
  --network web \
  --restart always \
  --expose 80 \
mikoposoft/pharmacyci3:old



















